# Generated by Django 5.0.1 on 2024-03-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainmodel',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='trainmodel',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
