# Generated by Django 5.0.1 on 2024-02-20 20:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='identikitsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identikit', models.ImageField(upload_to='criminal/media/identikits')),
            ],
        ),
        migrations.CreateModel(
            name='photosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='criminal/media/photos')),
            ],
        ),
        migrations.CreateModel(
            name='criminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(default='', max_length=30)),
                ('name', models.CharField(default='', max_length=30)),
                ('alias', models.CharField(default='', max_length=20)),
                ('case', models.CharField(default='', max_length=20, null=True)),
                ('description', models.CharField(default='', max_length=200)),
                ('criminal_record', models.CharField(default='', max_length=200)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('identikits', models.ManyToManyField(blank=True, null=True, to='criminal.identikitsmodel')),
                ('photos', models.ManyToManyField(to='criminal.photosmodel')),
            ],
        ),
    ]
