# Generated by Django 5.0.1 on 2024-02-29 13:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminal',
            name='specialty',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
    ]
