# Generated by Django 5.0.1 on 2024-02-21 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminal',
            name='mainPhoto',
            field=models.ImageField(default='', upload_to='criminal/media/photos/'),
        ),
        migrations.AlterField(
            model_name='identikitsmodel',
            name='identikit',
            field=models.ImageField(upload_to='criminal/media/identikits/'),
        ),
        migrations.AlterField(
            model_name='photosmodel',
            name='photo',
            field=models.ImageField(upload_to='criminal/media/photos/'),
        ),
    ]
