# Generated by Django 5.0.1 on 2024-03-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal', '0002_criminal_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminal',
            name='phone',
            field=models.IntegerField(blank=True, default=0, max_length=15, null=True),
        ),
    ]
