# Generated by Django 5.0.1 on 2024-02-21 19:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal', '0002_criminal_mainphoto_alter_identikitsmodel_identikit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminal',
            name='birthday',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='alias',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='case',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='criminal_record',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
