# Generated by Django 5.0.1 on 2024-02-21 20:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal', '0003_criminal_birthday_alter_criminal_alias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminal',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
