# Generated by Django 5.0.1 on 2024-02-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal', '0004_alter_criminal_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminal',
            name='ci',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='photos',
            field=models.ManyToManyField(blank=True, null=True, to='criminal.photosmodel'),
        ),
    ]
