# Generated by Django 5.0.1 on 2024-02-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal', '0005_criminal_ci_alter_criminal_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminal',
            name='mainPhoto',
            field=models.ImageField(default='', upload_to='criminal/photos/'),
        ),
        migrations.AlterField(
            model_name='identikitsmodel',
            name='identikit',
            field=models.ImageField(upload_to='criminal/identikits/'),
        ),
        migrations.AlterField(
            model_name='photosmodel',
            name='photo',
            field=models.ImageField(upload_to='criminal/photos/'),
        ),
    ]
