# Generated by Django 5.0.1 on 2024-02-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal', '0006_alter_criminal_mainphoto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminal',
            name='alias',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='case',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='ci',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='lastname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
