# Generated by Django 5.0.11 on 2025-02-05 23:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sketches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas', models.BooleanField(default=True)),
                ('input', models.ImageField(upload_to='sketches/input/')),
                ('output', models.ImageField(default='', null=True, upload_to='sketches/output/')),
                ('description', models.CharField(default='', max_length=200)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
