# Generated by Django 5.0.1 on 2024-01-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sketches',
            name='image',
            field=models.ImageField(default='uploads/sketch.jpg', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
