# Generated by Django 5.0.1 on 2024-02-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketches', '0002_sketches_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sketches',
            name='name',
        ),
        migrations.AddField(
            model_name='sketches',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sketches',
            name='image',
            field=models.ImageField(upload_to='sketches/uploads/'),
        ),
    ]
