# Generated by Django 5.0.11 on 2025-02-05 23:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.ImageField(default='', upload_to='images/input/')),
                ('database', models.CharField(default='', max_length=20, null=True)),
                ('results', models.JSONField(default=dict, null=True)),
                ('description', models.CharField(default='', max_length=200)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
