# Generated by Django 5.0.1 on 2024-02-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_images_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='input',
            field=models.ImageField(default='', upload_to='images/input/'),
        ),
    ]
